# conda env create --file environment.yml
# mamba env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - gh
  - pip
  {% if cookiecutter.project_packages == "All" -%}
# Download NodeJS and Quarto
# https://nodejs.org/en/download/package-manager
# https://quarto.org/docs/download/
  - nodejs
  - jupyterlab
  - jupyterlab-fonts
  - jupyterlab-quarto
  - catppuccin-jupyterlab
  {% endif -%}
  - jupyter
  {% if cookiecutter.project_packages == "All" -%}
  - keras
  - lightgbm
  {% endif -%}
  - matplotlib
  {% if cookiecutter.project_packages == "All" -%}
  - missingno
  {% endif -%}
  - nbdime
  - numpy
  - pandas
  {% if cookiecutter.project_packages == "All" -%}
  - pandas-flavor
  - pandas-profiling
  {% endif -%}
  - plotly
  - pyjanitor
  {% if cookiecutter.project_packages == "All" -%}
  - pylint
  {% endif -%}
  - pyprojroot
  {% if cookiecutter.project_packages == "All" -%}
  - pyspark
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  {% if cookiecutter.project_packages == "All" -%}
  - python-dotenv
  - scikit-learn
  {% endif -%}
  - seaborn
  {% if cookiecutter.project_packages == "All" -%}
  - statsmodels
  - tensorflow
  {% endif -%}
